[package]
name = "total-space"
version = "0.1.0"
authors = ["Oren Ben-Kiki <oren@ben-kiki.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
